[package]
name = "evgl-cli"
version = "0.1.0"

[dependencies.flags-2-env]
git = "https://github.com/ORESoftware/flags-2-env"
rev = "4eb9360d418ed64de994e4b1d6e43e7063219e02"
path = "vendor/flags-2-env"
